version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    logging:
      driver: json-file
      options:
        max-size: 50m

  static-nginx:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=mirror-fr-1.gladysproject.com
      - LETSENCRYPT_HOST=mirror-fr-1.gladysproject.com
      - LETSENCRYPT_EMAIL=hello@gladysproject.com
    volumes:
      - ./files:/usr/share/nginx/html:ro
      - "./conf/default.conf:/etc/nginx/default.conf:ro"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy